### ISSUE TITLE
comments so editor and submitter can talk?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_hq#50]
> i was thinking maybe you coudl allow comments so that an uploader and an admin could go back and forth about changes?

my first thoguht was if it was a node we could enable that no problem.  What do you think @almasaeed2010

**Comment by almasaeed2010** [comment]
Honestly I am not sure how we'd implement this with our setup. If we do create a node per submission then we'll need to mange that node's life. If we don't create a node, we'd need to implement comments manually. So this might be a fair bit of work. Could we instead (as a temporary solution) provide a `mailto:` link that would email the submitter/admin?

**Comment by mestato** [comment]
Sure. I think the loss there is the user/admin conversational history, which will forever be embedded in email instead of staying with the data. If there is ever a question of why changes were made or who requested them, it'll often be lost. So I think a conversation within the site is optimal. But while nice, maybe not necessary. We don't record any of that type of data now, afterall. Lets put it on a long term feature wish list.

**Comment by bradfordcondon** [comment]
lacey would like this for adoption.  

Options:

- Create a node for the pending submission.
- somehow add comments to the edit/submit entity page

**Comment by bradfordcondon** [comment]
implemented!  #92   Thanks @almasaeed2010
